### ISSUE TITLE
Congratulation!!

### ISSUE THREAD

**Issue by Jookie262** [JolouTheRookie/MemoryGame#2]
When the user is finished playing the game or all the cards are being match there should be a message in the end that congratulates the user.

**Comment by JolouTheRookie** [comment]
Maybe in order to this issue to be completed we need to add a button that ask the user if it wishes to come back to the main page

**Comment by Jookie262** [comment]
Added congratulations text design and sound effect d6c40424e7f2380ab184ba0f47237e3a07bbe177
